<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/JavaLearning/blob/master/Numpy_Trichy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[77,  6, 16, 75],
       [14, 21, 84, 22],
       [ 8, 51, 30, 74],
       [74, 98, 33, 65],
       [93, 68,  2, 72],
       [51, 67, 70, 78]])

In [ ]:
np.sort(a)

array([ 6,  6, 11, 20, 37, 41, 49, 50, 53, 70, 73, 82, 84, 87, 97])

In [ ]:
np.sort(b)

array([[ 6, 16, 75, 77],
       [14, 21, 22, 84],
       [ 8, 30, 51, 74],
       [33, 65, 74, 98],
       [ 2, 68, 72, 93],
       [51, 67, 70, 78]])

In [ ]:
np.sort(b,axis=0)

array([[ 8,  6,  2, 22],
       [14, 21, 16, 65],
       [51, 51, 30, 72],
       [74, 67, 33, 74],
       [77, 68, 70, 75],
       [93, 98, 84, 78]])

np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,883)

array([ 70,  97,  20,  87,  11,  53,  73,  84,  49,   6,  50,   6,  41,
        82,  37, 883])

In [ ]:
b

array([[77,  6, 16, 75],
       [14, 21, 84, 22],
       [ 8, 51, 30, 74],
       [74, 98, 33, 65],
       [93, 68,  2, 72],
       [51, 67, 70, 78]])

In [ ]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[77.,  6., 16., 75.,  1.],
       [14., 21., 84., 22.,  1.],
       [ 8., 51., 30., 74.,  1.],
       [74., 98., 33., 65.,  1.],
       [93., 68.,  2., 72.,  1.],
       [51., 67., 70., 78.,  1.]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[7.70000000e+01, 6.00000000e+00, 1.60000000e+01, 7.50000000e+01,
        7.96032703e-01],
       [1.40000000e+01, 2.10000000e+01, 8.40000000e+01, 2.20000000e+01,
        6.57579900e-01],
       [8.00000000e+00, 5.10000000e+01, 3.00000000e+01, 7.40000000e+01,
        4.44734314e-02],
       [7.40000000e+01, 9.80000000e+01, 3.30000000e+01, 6.50000000e+01,
        2.68175074e-01],
       [9.30000000e+01, 6.80000000e+01, 2.00000000e+00, 7.20000000e+01,
        8.34505437e-01],
       [5.10000000e+01, 6.70000000e+01, 7.00000000e+01, 7.80000000e+01,
        8.85831442e-01]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
# code
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0)

array([[70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37]])

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1)

array([[70],
       [97],
       [20],
       [87],
       [11],
       [53],
       [73],
       [84],
       [49],
       [ 6],
       [50],
       [ 6],
       [41],
       [82],
       [37]])

np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  3,  5,  6,  7, 13]),)

In [ ]:
# replace all value > 50 with 0
np.where(a>50,0,a)

array([ 0,  0, 20,  0, 11,  0,  0,  0, 49,  6, 50,  6, 41,  0, 37])

In [ ]:
np.where(a%2==0,0,a)

array([ 0, 97,  0, 87, 11, 53, 73,  0, 49,  0,  0,  0, 41,  0, 37])

np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
np.argmax(a)

np.int64(1)

In [ ]:
np.argmax(b,axis=1)

array([0, 2, 3, 1, 0, 3])

In [ ]:
b

array([[77,  6, 16, 75],
       [14, 21, 84, 22],
       [ 8, 51, 30, 74],
       [74, 98, 33, 65],
       [93, 68,  2, 72],
       [51, 67, 70, 78]])

In [ ]:
np.argmax(b,axis=1)

array([0, 2, 3, 1, 0, 3])

In [ ]:
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
# np.argmin
np.argmin(a)

np.int64(9)

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
np.cumsum(a)

array([ 70, 167, 187, 274, 285, 338, 411, 495, 544, 550, 600, 606, 647,
       729, 766])

In [ ]:
b

array([[77,  6, 16, 75],
       [14, 21, 84, 22],
       [ 8, 51, 30, 74],
       [74, 98, 33, 65],
       [93, 68,  2, 72],
       [51, 67, 70, 78]])

In [ ]:
np.cumsum(b, axis=0)

array([[ 77,   6,  16,  75],
       [ 91,  27, 100,  97],
       [ 99,  78, 130, 171],
       [173, 176, 163, 236],
       [266, 244, 165, 308],
       [317, 311, 235, 386]])

In [ ]:
np.cumsum(b)

array([  77,   83,   99,  174,  188,  209,  293,  315,  323,  374,  404,
        478,  552,  650,  683,  748,  841,  909,  911,  983, 1034, 1101,
       1171, 1249])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                 70,                6790,              135800,
                  11814600,           129960600,          6887911800,
              502817561400,      42236675157600,    2069597082722400,
         12417582496334400,  620879124816720000, 3725274748900320000,
       5162312115236707072, -965520245909707264, 1169239048759934464])

In [ ]:
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
np.cumprod(b,axis=1)

array([[      77,      462,     7392,   554400],
       [      14,      294,    24696,   543312],
       [       8,      408,    12240,   905760],
       [      74,     7252,   239316, 15555540],
       [      93,     6324,    12648,   910656],
       [      51,     3417,   239190, 18656820]])

In [ ]:
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
np.percentile(a,100)

np.float64(97.0)

In [ ]:
np.percentile(a,0)

np.float64(6.0)

In [ ]:
np.percentile(a,50)

np.float64(50.0)

In [ ]:
np.median(a)

np.float64(50.0)

np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 1, 1, 1, 2, 2, 0, 2, 3, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [ ]:
np.histogram(b, bins=[0,50,100])

(array([ 9, 15]), array([  0,  50, 100]))

np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
item = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,item)

array([ True, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False])

In [ ]:
a[np.isin(a,item)]

array([70, 20, 50])

np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
np.flip(a)

array([37, 82, 41,  6, 50,  6, 49, 84, 73, 53, 11, 87, 20, 97, 70])

In [ ]:
b

array([[77,  6, 16, 75],
       [14, 21, 84, 22],
       [ 8, 51, 30, 74],
       [74, 98, 33, 65],
       [93, 68,  2, 72],
       [51, 67, 70, 78]])

In [ ]:
np.flip(b)

array([[78, 70, 67, 51],
       [72,  2, 68, 93],
       [65, 33, 98, 74],
       [74, 30, 51,  8],
       [22, 84, 21, 14],
       [75, 16,  6, 77]])

In [ ]:
np.flip(b,axis=1)

array([[75, 16,  6, 77],
       [22, 84, 21, 14],
       [74, 30, 51,  8],
       [65, 33, 98, 74],
       [72,  2, 68, 93],
       [78, 70, 67, 51]])

np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code
a

array([70, 97, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
np.put(a,[0,1],[124,84])

np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([124,  84,  20,  87,  11,  53,  73,  84,  49,   6,  50,   6,  41,
        82,  37])

In [ ]:
np.delete(a,0)

array([84, 20, 87, 11, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

In [ ]:
np.delete(a,[0,2,4])

array([84, 87, 53, 73, 84, 49,  6, 50,  6, 41, 82, 37])

# New Section

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([[3,4,5,6,7]])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,10)]

/tmp/ipykernel_630/2623329359.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,10)]


array([], dtype=int64)

# New Section

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([124,  84,  20,  87,  11,  53,  73,  84,  49,   6,  50,   6,  41,
        82,  37])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 75, 25, 53, 73, 75, 49, 25, 50, 25, 41, 75, 37])