<a href="https://colab.research.google.com/github/surajsarkar3526-cyber/JavaLearning/blob/master/Numpy_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Numpy Arrays

In [ ]:
# np.array
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
# 2D And 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3,4], dtype=int)

array([1, 2, 3, 4])

In [ ]:
# np.arrange
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# np.reshape
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# np.zeroes and np.onces
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((4,3))

array([[0.89659826, 0.65496949, 0.50701518],
       [0.04416593, 0.50069462, 0.67245445],
       [0.01773308, 0.62382169, 0.73535794],
       [0.13972995, 0.63740942, 0.56782712]])

In [ ]:
# np.linspace
np.linspace(10,-10,10)

array([ 10.        ,   7.77777778,   5.55555556,   3.33333333,
         1.11111111,  -1.11111111,  -3.33333333,  -5.55555556,
        -7.77777778, -10.        ])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=np.int32).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

In [ ]:
# itemSize
a2.itemsize

4

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int32
int64


Changing Datatype

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operation

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# vector operations
#arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[15., 88., 15.],
       [78., 26.,  4.],
       [55., 46., 19.]])

In [ ]:
# max/min/sum/prod
# 0 -> column and 1 -> rows
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))
np.max(a1,axis = 1)
np.min(a1,axis=0)

88.0
4.0
346.0
7720888032000.0


array([15., 26.,  4.])

In [ ]:
# mean/median/std/var
np.median(a1,axis=1)
np.mean(a1,axis=0)
np.std(a1,axis=0)
np.var(a1,axis=1)

array([1184.22222222,  962.66666667,  234.        ])

In [ ]:
# trignomatric functions
np.sin(a1)

array([[ 0.65028784,  0.0353983 ,  0.65028784],
       [ 0.51397846,  0.76255845, -0.7568025 ],
       [-0.99975517,  0.90178835,  0.14987721]])

In [ ]:
# dot product
a2 = np.arange(12).reshape((3,4))
a3 = np.arange(12,24).reshape((4,3))
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponenets
np.log(a1)
np.exp(a1)

array([[3.26901737e+06, 1.65163625e+38, 3.26901737e+06],
       [7.49841700e+33, 1.95729609e+11, 5.45981500e+01],
       [7.69478527e+23, 9.49611942e+19, 1.78482301e+08]])

In [ ]:
# round/floor/ceil
print(np.round(np.random.random((3,4))*100))
print(np.floor(np.random.random((3,4))*100))
np.ceil((np.random.random((3,4))*100))

[[ 36.  73.  20. 100.]
 [ 60.  16.  50.  45.]
 [ 19.  19.  40.  37.]]
[[33. 35. 13.  2.]
 [38. 70. 43. 91.]
 [65.  1. 91. 52.]]


array([[15., 35., 96., 97.],
       [28., 61., 67., 77.],
       [10., 79., 15., 18.]])

Indexing and slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[-1]

np.int64(9)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[2][2]

np.int64(10)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
a3[0][0][0]

np.int64(0)

In [ ]:
a3[1][1][0]

np.int64(6)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[1, ::3]

array([4, 7])

In [ ]:
a2[::, 1::]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [ ]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  for j in i:
    print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [ ]:
# reshape

In [ ]:
# transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]